### ISSUE TITLE
Username or password are incorrect

### ISSUE THREAD

**Issue by chephei** [inshopgroup/inshop-crm-api#8]
Hello,

I'm trying to start your system to one of my clouds, but I can't get success, when accessing the client, he always shows the message "Username or password are incorrect":
**I'm trying to access the external ip 192.168.15.15:8080**
![image](https://user-images.githubusercontent.com/31193948/99997484-fc3d7900-2d9b-11eb-8d04-e15cfd6306dc.png)

I can put it to work on my machine as a local host, but when I put it in production it presents this error, I need to do something else, I will leave it below as I do to lift the container.

```
git clone git@github.com:inshopgroup/inshop-crm-api.git
sudo sysctl -w vm.max_map_count=262144
echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
docker-compose up -d
docker-compose exec --user=root php sh ./setup.sh
```

**docker ps** 

```
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS              PORTS                              NAMES
79345753f5b1        inshopgroup/docker-inshop-crm-api-nginx-prod:latest     "/docker-entrypoint.…"   14 minutes ago      Up 13 minutes       0.0.0.0:8888->80/tcp               inshopcrm-api_nginx_1
939f330c6748        inshopgroup/docker-inshop-crm-api-php-fpm-prod:latest   "docker-php-entrypoi…"   14 minutes ago      Up 13 minutes       9000/tcp                           inshopcrm-api_php_1
fce301b30094        redis:latest                                            "docker-entrypoint.s…"   14 minutes ago      Up 14 minutes       6379/tcp                           inshopcrm-api_redis_1
479934213ede        inshopgroup/inshop-crm-client                           "nginx -g 'daemon of…"   14 minutes ago      Up 14 minutes       0.0.0.0:8080->80/tcp               inshopcrm-api_client_1
62b74e22049d        docker.elastic.co/elasticsearch/elasticsearch:6.3.1     "/usr/local/bin/dock…"   14 minutes ago      Up 13 minutes       9300/tcp, 0.0.0.0:9222->9200/tcp   inshopcrm-api_elasticsearch_1
e272ff245633        postgres:11.4-alpine                                    "docker-entrypoint.s…"   14 minutes ago      Up 14 minutes       0.0.0.0:54321->5432/tcp            inshopcrm-api_db_1
```

**docker network ls**

```
NETWORK ID          NAME                  DRIVER              SCOPE
fc412303260c        bridge                bridge              local
69d051fb1822        host                  host                local
67d632a81424        inshopcrm-api_api     bridge              local
4703ef79d62e        inshopcrm-api_esnet   bridge              local
b0e970624857        none                  null                local
```

**docker-compose ps**

```
        Name                       Command               State                Ports              
--------------------------------------------------------------------------------------------------
sigcrm_client_1          nginx -g daemon off;             Up      0.0.0.0:8080->80/tcp            
sigcrm_db_1              docker-entrypoint.sh postgres    Up      0.0.0.0:54321->5432/tcp         
sigcrm_elasticsearch_1   /usr/local/bin/docker-entr ...   Up      0.0.0.0:9222->9200/tcp, 9300/tcp
sigcrm_nginx_1           /docker-entrypoint.sh ngin ...   Up      0.0.0.0:8888->80/tcp            
sigcrm_php_1             docker-php-entrypoint php-fpm    Up      9000/tcp                        
sigcrm_redis_1           docker-entrypoint.sh redis ...   Up      6379/tcp 
```

**my env file:**

```
# This file is a "template" of which env vars need to be defined for your application
# Copy this file to .env file for development, create environment variables when deploying to production
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

PORT_DATABASE=54321
PORT_API=8888
PORT_ELASTIC=9222
PORT_CLIENT=8080

###> symfony/framework-bundle ###
APP_ENV=prod
APP_SECRET=verystrongpassword
TRUSTED_PROXIES=127.0.0.1,127.0.0.2
TRUSTED_HOSTS=127.0.0.1,192.168.15.15,localhost,crm.mydomain.com
###< symfony/framework-bundle ###

###> nelmio/cors-bundle ###
CORS_ALLOW_ORIGIN=^https?://localhost(:[0-9]+)?$
###< nelmio/cors-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data.db"
# Configure your db driver and server_version in config/packages/doctrine.yaml
DATABASE_DRIVER=pdo_pgsql
DATABASE_HOST=db
DATABASE_PORT=5432
DATABASE_NAME=api
DATABASE_USER=api
DATABASE_PASSWORD=verystrongpassword
###< doctrine/doctrine-bundle ###

###> lexik/jwt-authentication-bundle ###
JWT_PASSPHRASE=verystrongpassword
###< lexik/jwt-authentication-bundle ###

###> sentry/sentry-symfony ###
SENTRY_DSN=
###< sentry/sentry-symfony ###

COMPOSE_PROJECT_NAME=sigcrm

###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=null://localhost
###< symfony/swiftmailer-bundle ###

CLIENT_URL=http://localhost:3000

###> google/apiclient ###
GOOGLE_API_KEY=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
###< google/apiclient ###

###> amazon/s3_keys ###
AWS_S3_ACCESS_ID=
AWS_S3_ACCESS_SECRET=
###< amazon/s3_keys ###

###> amazon/bucketNames ###
AWS_S3_BUCKET_FILE_NAME=file
AWS_S3_BUCKET_IMAGE_NAME=image
###< amazon/bucketNames ###

###> amazon/bucketRegion ###
AWS_S3_BUCKET_REGION=eu-west-1
###< amazon/bucketRegion ###

###> Redis  ###
REDIS_HOST=redis
REDIS_PORT=6379
###< Redis ###
```
**My docker-compose.yml**

```
version: '3.7'

services:
  client:
    image: inshopgroup/inshop-crm-client
    env_file:
      - ./.env
    restart: always
    ports:
      - ${PORT_CLIENT}:80
    networks:
      - api

  php:
    image: inshopgroup/docker-inshop-crm-api-php-fpm-prod:latest
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - .:/var/www:rw,cached
      - files-data:/var/www/var/files:rw
    networks:
      - api

  nginx:
    image: inshopgroup/docker-inshop-crm-api-nginx-prod:latest
    env_file:
      - ./.env
    depends_on:
      - php
    volumes:
      - ./public:/var/www/public:ro
    ports:
      - ${PORT_API}:80
    networks:
      - api

  db:
    image: postgres:11.4-alpine
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - ${PORT_DATABASE}:5432
    networks:
      - api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    env_file:
      - ./.env
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - ${PORT_ELASTIC}:9200
    networks:
      - api
      - esnet

  redis:
    image: redis:latest
    env_file:
      - ./.env
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - api

volumes:
  es-data: {}
  db-data: {}
  redis-data: {}
  files-data: {}
  images-data: {}

networks:
    esnet:
    api:
```

Would you have anything else to do?

Ty
